#include <Kokkos_Core.hpp>
#include <cstdio>

int main(int argc, char* argv[]) {
    Kokkos::initialize(argc, argv);
    {
        int N = 10;

        //Allocate a View on the Device (e.g., GPU VRAM)
        Kokkos::View<double*> d_data("DeviceData", N);

        //Fill the View on the Device
        Kokkos::parallel_for("FillDevice", N, KOKKOS_LAMBDA(const int i) {
            d_data(i) = (double)i * 10.0;
        });
        Kokkos::fence(); // Wait for GPU to finish

        printf("Data generated on the Device.\n");

        // --- THE SOLUTION TO THE CLIFFHANGER ---
        // We cannot printf d_data(0) here if we are running on a GPU.
        // Instead, we must create a "Host Mirror" and copy the data over.

	// Create a Host Mirror
        // A HostMirror is guaranteed to live in CPU RAM, but it will have the 
        // exact same dimensions and layout as your device view.
        // We use 'auto' because the exact C++ type generated by Kokkos is highly complex!
        auto h_data = Kokkos::create_mirror_view(d_data);

        // Deep Copy (Device to Host)
        // This physically moves the data across the PCIe bus from VRAM to RAM.
        Kokkos::deep_copy(h_data, d_data);

        printf("\n--- Data copied to Host (CPU) ---\n");
        
        // Safely read and modify data on the CPU
        for(int i = 0; i < N; ++i) {
            printf("h_data(%d) = %f\n", i, h_data(i));
            // Let's modify the data on the CPU
            h_data(i) += 1.0; 
        }

        printf("\nModified data on the CPU. Copying back to Device...\n");

        // Deep Copy (Host to Device)
        // Move the modified data back to the GPU for further physics calculations!
        Kokkos::deep_copy(d_data, h_data);
        Kokkos::fence();

        printf("Round trip complete!\n");

    } // Scope braces ensure Views are deallocated before finalize
    Kokkos::finalize();
    return 0;
}
